### ISSUE TITLE
symmetric gradient on test function?

### ISSUE THREAD

**Issue by wence-** [florianwechsung/alfi#6]
In the definition of the residual (e.g. here)

https://github.com/florianwechsung/alfi/blob/8e61975b1bb01a5f783ff42e9ac859d1d74d3ea4/alfi/solver.py#L617

The test function is just `grad(v)` rather than `sym(grad(v))`. Does this matter at all?

**Comment by florianwechsung** [comment]
@wence- This doesn't matter (to floating point precision). Note that by the definition of the dot product

`sym(A) : B = sym(A) : B.T`

and hence `sym(A) : B = sym(A) : (B + B.T)/2 = sym(A) : sym(B)`

**Comment by wence-** [comment]
Thanks.
